apiVersion: v1
kind: Service
metadata:
  labels:
    app: 221058005_kavya
  name: 221058005_kavya
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: 221058005_kavya
